<?php


require_once($CFG->libdir.'/formslib.php');
/**
 * Created by IntelliJ IDEA.
 * User: tamara
 * Date: 08.06.17
 * Time: 10:44
 */
class block_qrcode_form extends moodleform {

    public function  definition()
    {
        global $CFG;
        $mform = $this->_form;
        $this->add_action_buttons(false, "Download");
    }

    public function validation($data, $files)
    {
        redirect(new moodle_url('/moodle/blocks/qrcode/download.php'));

        return parent::validation($data, $files); // TODO: Change the autogenerated stub
    }
}