name: Moodle Plugin Release

on:
  release:
    types:
      - published

jobs:
  call-release-workflow:
    name: "Release Workflow"
    uses: learnweb/moodle-workflows-learnweb/.github/workflows/moodle-release.yml@main
    with:
      plugin-name: 'block_qrcode'
    secrets: inherit
